openapi: 3.0.1
info:
  title: Simple Payment API
  description: This API exposes endpoints to manage payments.
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /transactions:
    post:
      tags:
      - Transaction API
      summary: Create a Transaction
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionRequestDto'
        required: true
      responses:
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransactionResponseDto'
  /accounts:
    post:
      tags:
      - Account API
      summary: Create an Account
      operationId: create_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequestDto'
        required: true
      responses:
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountResponseDto'
  /accounts/{accountId}:
    get:
      tags:
      - Account API
      summary: Retrieve an Account by Id
      operationId: get
      parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveAccountDto'
        "500":
          description: Internal Server Error
        "404":
          description: Not Found
components:
  schemas:
    CreateTransactionRequestDto:
      required:
      - account_id
      - amount
      - operation_type_id
      type: object
      properties:
        amount:
          pattern: "^[0-9]+\\.[0-9]{2}$"
          type: string
          example: "10.32"
        operation_type_id:
          maximum: 4
          minimum: 1
          type: integer
          format: int32
          example: 1
        account_id:
          type: integer
          format: int32
    CreateTransactionResponseDto:
      type: object
      properties:
        amount:
          type: string
          example: "100.77"
        transaction_id:
          type: integer
          format: int32
          example: 1
        operation_type:
          type: integer
          format: int32
          example: 3
        account_id:
          type: integer
          format: int32
          example: 10
    CreateAccountRequestDto:
      type: object
      properties:
        documentNumber:
          pattern: "^[0-9]{9}$|^[0-9]{11}$"
          type: string
    CreateAccountResponseDto:
      type: object
      properties:
        account_id:
          type: string
          example: "10"
        document_number:
          type: string
          example: "123456789"
    RetrieveAccountDto:
      type: object
      properties:
        account_id:
          type: string
          example: "10"
        document_number:
          type: string
          example: "123456789"
