services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=strongpass
      - MYSQL_DATABASE=bank
      - MYSQL_ROOT_PASSWORD=root
  # app:
  #   image: app:0.0.1-SNAPSHOT
  #   depends_on: 
  #     - mysql
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - MYSQL_USER=myuser
  #     - MYSQL_PASSWORD=strongpass
  #     - MYSQL_DATABASE=bank
    