services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=strongpass
      - MYSQL_DATABASE=bank
      - MYSQL_ROOT_PASSWORD=root
  app:
    build: .
    depends_on: 
      - mysql
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=strongpass
      - MYSQL_DATABASE=bank
      - MYSQL_HOST=mysql
    