/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.simple_payment_aot;

import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();

    }
}
