server:
  port : 8081

spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/bank"
    username: "${MYSQL_USER:myuser}"
    password: "${MYSQL_PASSWORD:strongpass}"
  jpa:
    hibernate:
      ddl-auto: "update"