---
name: default
spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/bank"
    username: "${MYSQL_USER:myuser}"
    password: "${MYSQL_PASSWORD:strongpass}"
  jpa:
    hibernate:
      ddl-auto: "update"

---
name: test
spring:
  datasource:
    url: "jdbc:h2:mem:bank"
    username: "test"
    password: "test"
  jpa:
    hibernate:
      ddl-auto: "create"